#!/usr/bin/env python

import sys
import xml.dom.minidom

def usage():
    print("Usage: %s [-n] file.xml" %sys.argv[0])
    sys.exit(1)

# handle debug and xml file
debug=False
if len(sys.argv) == 3:
    debug=True
    xmlfile = sys.argv[2]
    if sys.argv[1] != "-n":
        usage()
elif len(sys.argv) == 2:
    xmlfile = sys.argv[1]
else:
    usage()

_xml = ""
file = open(xmlfile)
for line in file.readlines():
    _xml += line.strip() + "\n"
file.close()
_xml = _xml.replace("\n", "")

# now clean up that sucker
xmldata = xml.dom.minidom.parseString(_xml)
file = open(xmlfile, "w")
xml = xmldata.toprettyxml()
file.write(xml)
file.close()
