#!/usr/bin/env python

import os
import string
import sys
import zipfile

if len(sys.argv) != 4:
    sys.stderr.write(("{} {zip a} {zip b} {set1|set2}\n".format(sys.argv[0]))
    sys.exit(3)

zip1 = sys.argv[1]
zip2 = sys.argv[2]

for f in [zip1, zip2]:
    if not os.path.isfile(f):
        sys.stderr.write("{} is not a file!\n".format(f))
        sys.exit(1)

zip1_contents = zipfile.ZipFile(zip1).namelist()
zip2_contents = zipfile.ZipFile(zip2).namelist()

zip1_not_zip2 = set(zip1_contents).difference(set(zip2_contents))
zip2_not_zip1 = set(zip2_contents).difference(set(zip1_contents))

if sys.argv[3] == "set1":
    print(string.join(zip1_not_zip2, "\n"))
if sys.argv[3] == "set2":
    print(string.join(zip2_not_zip1, "\n"))

